import { ActionItem, Decision } from '../types';

export function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generates and triggers download of Action Items as CSV.
 */
export function exportTasksToCSV(tasks: ActionItem[], filename = 'meetflow-action-items.csv'): string {
  const headers = [
    'Task ID',
    'Task Name',
    'Assignee',
    'Assignee Role',
    'Deadline',
    'Original Phrase',
    'Priority',
    'Status',
    'AI Confidence (%)',
    'Confirmed',
    'Meeting Title',
    'Source Quote',
  ];

  const rows = tasks.map((t) => [
    `"${t.id}"`,
    `"${(t.task || '').replace(/"/g, '""')}"`,
    `"${(t.assignee || 'Unassigned').replace(/"/g, '""')}"`,
    `"${(t.assigneeRole || '').replace(/"/g, '""')}"`,
    `"${(t.deadline || 'No deadline').replace(/"/g, '""')}"`,
    `"${(t.originalDeadlinePhrase || '').replace(/"/g, '""')}"`,
    `"${t.priority}"`,
    `"${t.status}"`,
    `"${t.confidence}"`,
    `"${t.isConfirmed ? 'Yes' : 'No'}"`,
    `"${(t.meetingTitle || '').replace(/"/g, '""')}"`,
    `"${(t.sourceText || '').replace(/"/g, '""')}"`,
  ]);

  const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  downloadFile(csvContent, filename, 'text/csv;charset=utf-8;');
  return csvContent;
}

/**
 * Generates formatted Markdown representation of Action Items.
 */
export function exportTasksToMarkdown(tasks: ActionItem[], meetingTitle = 'MeetFlow AI Action Items'): string {
  let md = `# ${meetingTitle}\n`;
  md += `*Generated by MeetFlow AI on ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}*\n\n`;

  md += `## 📋 Action Items (${tasks.length})\n\n`;

  tasks.forEach((t, i) => {
    const statusBox = t.status === 'done' ? '[x]' : '[ ]';
    const confidenceBadge = t.confidence >= 90 ? '🟢 High' : t.confidence >= 70 ? '🟡 Medium' : '🔴 Needs Review';
    md += `### ${i + 1}. ${statusBox} ${t.task}\n`;
    md += `- **Assignee:** ${t.assignee || 'Unassigned'} (${t.assigneeRole || 'Team Member'})\n`;
    md += `- **Deadline:** ${t.deadline || 'None'} *(spoken: "${t.originalDeadlinePhrase || ''}")*\n`;
    md += `- **Priority:** \`${t.priority}\` | **Status:** \`${t.status.toUpperCase()}\` | **AI Confidence:** ${t.confidence}% (${confidenceBadge})\n`;
    if (t.sourceText) {
      md += `> **Source Evidence:** "${t.sourceText}"\n`;
    }
    md += `\n---\n\n`;
  });

  downloadFile(md, 'meetflow-action-items.md', 'text/markdown;charset=utf-8;');
  return md;
}

/**
 * Generates Jira-compatible issue import table/text.
 */
export function exportTasksToJira(tasks: ActionItem[]): string {
  let jira = `|| Issue Type || Summary || Assignee || Priority || Due Date || Description ||\n`;
  tasks.forEach((t) => {
    jira += `| Task | ${t.task} | ${t.assignee || ''} | ${t.priority} | ${t.deadline || ''} | Extracted by MeetFlow AI (${t.confidence}% confidence). Source: "${t.sourceText || ''}" |\n`;
  });

  downloadFile(jira, 'meetflow-jira-tasks.txt', 'text/plain;charset=utf-8;');
  return jira;
}

/**
 * Generates Trello-compatible card import format.
 */
export function exportTasksToTrello(tasks: ActionItem[]): string {
  const lines = tasks.map((t) => {
    return `${t.task} @${(t.assignee || '').replace(/\s+/g, '').toLowerCase()} due:${t.deadline || ''} [Priority: ${t.priority}]`;
  });
  const content = lines.join('\n');
  downloadFile(content, 'meetflow-trello-cards.txt', 'text/plain;charset=utf-8;');
  return content;
}

/**
 * Generates full Executive Decisions & Topics Digest.
 */
export function exportDecisionsDigest(decisions: Decision[], title = 'Executive Decision Record'): string {
  let doc = `# ${title}\n`;
  doc += `*MeetFlow AI Verified Governance & Consensus Log*\n\n`;

  const confirmed = decisions.filter((d) => d.status === 'confirmed');
  const pending = decisions.filter((d) => d.status === 'pending');
  const open = decisions.filter((d) => d.status === 'open');

  doc += `## ✅ Confirmed Organizational Decisions (${confirmed.length})\n\n`;
  confirmed.forEach((d) => {
    doc += `### ${d.text}\n`;
    doc += `- **Quorum / Consensus:** ${d.quorumStatus || 'Unanimous'}\n`;
    doc += `- **Confidence:** ${d.confidence}%\n`;
    doc += `- **Details:** ${d.details || ''}\n`;
    if (d.sourceText) doc += `> "${d.sourceText}"\n`;
    doc += `\n`;
  });

  doc += `\n## ⏳ Decisions Pending Approval (${pending.length})\n\n`;
  pending.forEach((d) => {
    doc += `### ${d.text}\n`;
    doc += `- **Status:** ${d.quorumStatus || 'Awaiting vote'}\n`;
    doc += `- **Notes:** ${d.aiSuggestion || ''}\n`;
    if (d.sourceText) doc += `> "${d.sourceText}"\n`;
    doc += `\n`;
  });

  doc += `\n## 💬 Open Discussions & Unresolved Debates (${open.length})\n\n`;
  open.forEach((d) => {
    doc += `### ${d.text}\n`;
    doc += `- **Debate:** ${d.details || ''}\n`;
    doc += `- **AI Action Recommendation:** ${d.aiSuggestion || ''}\n\n`;
  });

  downloadFile(doc, 'meetflow-executive-decision-matrix.md', 'text/markdown;charset=utf-8;');
  return doc;
}
